
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>喵魂图床</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="喵魂图床,图床,相册,外链图床">
    <meta name="author" content="喵魂图床,图床,相册,外链图床">

    <!-- Le styles -->
    <link href="/public/css/bootstrap.css" rel="stylesheet">
    <link href="/public/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/public/css/docs.css" rel="stylesheet">


    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body data-spy="scroll" data-target=".subnav" data-offset="50">
	<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav">
						<li>
							<a href="http://disk.catsoul.cn">喵魂网盘</a>
						</li>
						<li class="active">
							<a href="http://1.wjtuku.sinaapp.com">喵魂图床</a>
						</li>
						<li>
							<a href="http://smgc.in">数码广场</a>
						</li>
						<li>
							<a href="http://wenjun.in">花生博客</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	<div class="container-fluid">
		<div class="row-fluid">
		
		<div class="span4">&nbsp;</div>
			<div class="span4">
				<div class="hero-unit">
					
					<div class="page-header">
						<h1><center>喵魂图床</center></h1>
						<hr>
						<h2>用户登录</h2>
					</div>
					
					<form class="form" method="post" action="/auth/login">
						<fieldset>
							<div class="control-group">
								<label class="control-label" for="input01"></label>
								<div class="controls">
									<input type="email" class="input-xlarge"  tabindex="1" placeholder="Email" name="email">
								</div>
							</div>
							<div class="control-group">
								<div class="controls">
									<input type="password" class="input-xlarge"  tabindex="2" placeholder="密码" name="password">
								</div>
							</div>
							<button type="submit" class="btn span3"><strong>登&nbsp;&nbsp;&nbsp;录</strong></button>
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<a href="#"><strong>忘记密码？</strong></a>
							<a href="/auth/showreg" class="btn pull-right"><strong>>>&nbsp;&nbsp;注册</strong></a>
						</fieldset>
					</form>
					<font color="red">*&nbsp;&nbsp;&nbsp;只支持FireFox与Chrome
						<br>*&nbsp;&nbsp;&nbsp;单文件大小300K
					</font>
					
				</div>
			</div>
			<div class="span6"></div>
			
	</div>

	 <footer class="footer">
				<div class="pull-left">
	 		<strong>© 2012 喵魂</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	 		<strong><a href="http://wenjun.in/?page_id=387">意见/建议/留言</a></strong>
	 	</div>
	 	<div class="pull-right">
			
			<a href="http://www.miibeian.gov.cn/" target="_blank"><strong>蜀ICP备11021029号</strong></a>&nbsp;&nbsp;&nbsp;&nbsp;
			<a href="http://sae.sina.com.cn" target="_blank"><img src="http://static.sae.sina.com.cn/image/poweredby/117X12px.gif" title="Powered by Sina App Engine"></a>
			<script src="http://s95.cnzz.com/stat.php?id=4232969&web_id=4232969" language="JavaScript"></script>
		</div>
			</footer>

  </body>
</html>
