<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>喵魂图床</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="喵魂图床,图床,相册,外链图床">
    <meta name="author" content="喵魂图床,图床,相册,外链图床">

    <!-- Le styles -->

    <link href="/public/css/bootstrap.css" rel="stylesheet">
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/public/js/jquery.js"></script>
    <script src="/public/js/bootstrap-transition.js"></script>
    <script src="/public/js/bootstrap-modal.js"></script>
    <script src="/public/js/bootstrap-tooltip.js"></script>
    <script src="/public/js/jquery.form.js"></script> 
    <script src="/public/js/home.js"></script>
<!--    <script type="text/javascript" src="/public/js/ZeroClipboard.js"></script>   --> 
  
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="/public/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/public/ico/favicon.ico">
  </head>
  <body>
  <div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav">
						<li>
							<a href="http://disk.catsoul.cn">喵魂网盘</a>
						</li>
						<li class="active">
							<a href="http://1.wjtuku.sinaapp.com">喵魂图床</a>
						</li>
						<li>
							<a href="http://smgc.in">数码广场</a>
						</li>
						<li>
							<a href="http://wenjun.in">花生博客</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">用户资料</li>
			  <br>
              <li><i class="icon-user"></i>&nbsp;&nbsp;&nbsp;<strong><a href="#edit_userinfo" data-toggle="modal"><?php echo $this->email;?></a>
              	<a href="javascript:logout()" class="btn pull-right"><i class="icon-off"></i></a></strong></li>
              
              <div class="modal hide fade" id="edit_userinfo">
  						<div class="modal-header">
    						<h3>修改用户信息</h3>
  						</div>
  						<div class="modal-body"><center>
    						 <form id="edit_userinfo_form" action="/auth/editpassword/" method="POST" enctype="multipart/form-data">
    						 	<input type="text" name="old_password" placeholder="请输入旧密码"><br>
    						 	<input type="password" name="new_password" placeholder="请输入新密码"><br>
    						 	<input type="password" name="confirm_password" placeholder="请再次输入新密码">
    						 	<div id="edit_userinfo_result"></div>
  						</center></div>
  						<div class="modal-footer">
  							<button type="submit" class="btn btn-primary start">
                    			<i class="icon-upload icon-white"></i>
                    			<span>提交</span>
                			</button>
                			</form>
    						<button class="btn btn-danger cancel" data-dismiss="modal">
                    		<i class="icon-remove icon-white"></i>
                    		<span>关闭窗口</span>
            				</button>
  					</div>
				</div>
				
			  <br>
			  <li>
				<div class="progress">
					<div class="bar"style="width: <?php echo $this->progress.'%';?>;"></div>
				</div>
			  </li>
			  <li><center><strong>
			  		已使用：<span class="badge badge-success"><?php echo round($this->used_volume,2);?>M</span>&nbsp;&nbsp;&nbsp;
			  		总容量：<span class="badge badge-success"><?php echo $this->user_volume;?>M</span>
			  	</strong></center></li>
			  </ul>
			  <hr>
			  
			  <ul class="nav nav-pills nav-stacked">
				<li class="nav-header"><strong>相&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;册
					<a class="btn pull-right" href="#add_gallery" data-toggle="modal" data-keyboard="false" data-backdrop="false"><i class="icon-plus"></i></a>
					<a class="btn pull-right" href="#del_gallery"  data-toggle="modal" data-keyboard="false" data-backdrop="false"><i class="icon-minus"></i></a>		
				</strong>
				<div class="modal hide fade" id="del_gallery">
  						<div class="modal-header">
    						<h3>删除相册</h3>
  						</div>
  						<div class="modal-body"><center>
								<table class="table table-striped table-bordered table-condensed">
	        						<thead>
          								<tr>
            								<th>#</th>
            								<th>相册名</th>
            								<th>相片数</th>
            								<th>创建时间</th>
          								</tr>
        							</thead>
        							<form id="del_gallery_form" action="/home/delgallery/" method="POST">
        							<tbody>
        							<?php 
        								$i = 0;
        								if(!empty($this->album))
        								{
        									foreach ($this->album as $row)
											{
												echo '<tr>';
												echo '<td><input type="checkbox" name="delete_id[]" value="'.$row['id'].'">&nbsp;&nbsp;'.$i.'</td>';
												echo '<td>'.$row['album_name'].'</td>';
												echo '<td>'.$row['picture_count'].'</td>';
												echo '<td>'.$row['create_time'].'</td>';
												$i++;
											}
        								}
									?>
        							</tbody>
      							</table>
      							<div id="del_result"></div>
  						</center></div>
  						<div class="modal-footer">
  							<button type="submit" class="btn btn-primary start">
                    			<i class="icon-upload icon-white"></i>
                    			<span>提交</span>
                			</button>
                			</form>
    						<button class="btn btn-danger cancel" data-dismiss="modal">
                    		<i class="icon-remove icon-white"></i>
                    		<span>关闭窗口</span>
            				</button>
  						</div>
				
		
				</li>
							
				<br>
				<?php 
					if($this->current == '0')
					{
						echo '<li class="active"><a href="/home/index"><i class="icon-home"></i>&nbsp;&nbsp;&nbsp;根目录</a></li>';
					}else {
						echo '<li><a href="/home/index"><i class="icon-home"></i>&nbsp;&nbsp;&nbsp;根目录</a></li>';
					}
					
					if(!empty($this->album))
					{
						foreach ($this->album as $row)
						{
							if($this->current == $row['id'])
							{
								echo '<li class="active"><a href="/home/index/id/'.$row['id'].'"><i class="icon-bookmark"></i>&nbsp;&nbsp;&nbsp;'.$row['album_name'].'</a></li>';
							}else {
								echo '<li><a href="/home/index/id/'.$row['id'].'"><i class="icon-bookmark"></i>&nbsp;&nbsp;&nbsp;'.$row['album_name'].'</a></li>';
							}
							
						}	
					}
					
				?>
				<div class="modal hide fade" id="add_gallery">
  						<div class="modal-header">
    						<h3>添加相册</h3>
  						</div>
  						<div class="modal-body"><center>
    						 <form id="gallery_name" action="/home/addgallery/" method="POST" enctype="multipart/form-data">
    						 	<input type="text" name="name" placeholder="请输入相册名">
    						 	<div id="gallery_result"></div>
  						</center></div>
  						<div class="modal-footer">
  							<button type="submit" class="btn btn-primary start">
                    			<i class="icon-upload icon-white"></i>
                    			<span>保存</span>
                			</button>
                			</form>
    						<button class="btn btn-danger cancel" data-dismiss="modal">
                    		<i class="icon-remove icon-white"></i>
                    		<span>关闭窗口</span>
            				</button>
  					</div>
				</div>
				<br>
            </ul>
            
			
			<div class="modal hide fade" id="myModal">
				<div class="modal-header">
    				<a class="close" data-dismiss="modal">×</a>
    				<h3>图片上传</h3>
  				</div>
				<div class="modal-body"><center>
					 <form id="myForm" action="/home/upload/" method="POST" enctype="multipart/form-data">
					 <input class="btn btn-primary" type="file" name="files[]" multiple>  
 				</center>
 				<div id="fileinfo" class="alert alert-block alert-success"></div>
    		</div>
				<div class="modal-footer">
				<select class="span5" name="gallery">
                <option value="0">请选择相册</option>
               <?php 
					if(!empty($this->album))
					{
						foreach ($this->album as $row)
						{
							echo '<li><a href="#"><i class="icon-picture"></i>&nbsp;&nbsp;&nbsp;'.$row['album_name'].'</a></li>';
							echo '<option value="'.$row['id'].'">'.$row['album_name'].'</option>';
						}	
					}
					
				?>
              </select>
				<button type="submit" class="btn btn-primary start" >
                    <i class="icon-upload icon-white"></i>
                    <span>上传图片</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>取消上传</span>
                </button>
                </form>
                <button class="btn btn-danger cancel" data-dismiss="modal">
                    <i class="icon-remove icon-white"></i>
                    <span>关闭窗口</span>
                </button>
				</div>
			</div>
			<center><a class="btn btn-primary btn-large" data-toggle="modal" href="#myModal">上传图片</a></center>
          </div><!--/.well -->
        </div><!--/span-->
        
		<div class="span9">
			<div class="row-fluid">
				<?php 
					$i = 0;
					if(count($this->picture)>0)
					{
						foreach ($this->picture as $row)
						{
							if($i % 4 == 0)
							{
								echo '<ul class="thumbnails example-sites">';
							}
							echo '<li class="span3">';			
							echo "<button type='button' class='btn' name='open_picture' value='".Zend_Json::encode($row)."'>";
                    		echo '<a name="a_picture" class="thumbnail btn" href="#open_image" data-toggle="modal"  data-keyboard="false" data-backdrop="false"><img src="'.$row['url'].'" width="210" height="210">';
                    		echo ''.$row['name'].'</a></button>';
                			echo '</li>';
							$i++;
							if($i % 4 == 0)
							{
								echo '</ul>';
							}
						}
					}

				?>	
				<div class="modal hide fade" id="open_image">
  					<div class="modal-header">
    					<h3><div id="return_img_value_header_name"></div></h3>
    					<h4><div id="return_img_value_header_time"></div></h4>
  					</div>
  					<div class="modal-body">
    					<div class="alert alert-block alert-info fade in" id="open_image_content">
    						<center><div id="return_img_value_body"></div></center>
          				</div>
          				<div id="return_img_value_body_tip"></div>
  					</div>
  					<div class="modal-footer">
  						<div id="return_img_value_footer"></div>
  				</div>
  				
			</div><!--/row-->
			
        </div><!--/span-->
    </div><!--/row-->

      <div class="pull-right"><?php echo $this->paginationControl($this->picture, 'Sliding', '/home/pagelist.phtml');?></div>
      
      
      
      
     <div class="modal hide fade" id="check_value">
  		<div class="modal-header">
    		<h3>温馨提示</h3>
  		</div>
  		<div class="modal-body">
    		<div class="alert alert-block alert-error fade in">
            	<p>您还没有激活帐户, 目前只有50M空间, 请到注册邮箱点击确认链接, 获取<strong>2G</strong>空间!</p>
          	</div>
          	<center><div id="return_value"></div></center>
  		</div>
  		<div class="modal-footer">
  			<a class="btn btn-danger" href="javascript:send_active_mail()">发送邮件</a>
  			<a class="btn btn-primary" href="javascript:check_active_mail()">激活后点击</a>
    		<button class="btn btn-danger cancel" data-dismiss="modal">
                    <i class="icon-remove icon-white"></i>
                    <span>关闭窗口</span>
            </button>
  		</div>
  		
  		
  		

		</div>
    </div><!--/.fluid-container-->

    
    
    <script> 
    $('#check_value').modal({
        backdrop:true,
        keyboard:true,
<?php 
	if($this->user_volume > 50)
	{
		echo "show:false";
	}else {
		echo "show:true";
	}
?>
    });
    </script>
    <footer class="footer">
				<div class="pull-left">
	 		<strong>© 2012 喵魂</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	 		<strong><a href="http://wenjun.in/?page_id=387">意见/建议/留言</a></strong>
	 	</div>
	 	<div class="pull-right">
			
			<a href="http://www.miibeian.gov.cn/" target="_blank"><strong>蜀ICP备11021029号</strong></a>&nbsp;&nbsp;&nbsp;&nbsp;
			<a href="http://sae.sina.com.cn" target="_blank"><img src="http://static.sae.sina.com.cn/image/poweredby/117X12px.gif" title="Powered by Sina App Engine"></a>
			<script src="http://s95.cnzz.com/stat.php?id=4232969&web_id=4232969" language="JavaScript"></script>
		</div>
			</footer>
  </body>
</html>
